// Mocks generated by Mockito 5.4.6 from annotations
// in zephyr/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i9;
import 'package:fpdart/fpdart.dart' as _i11;
import 'package:geolocator/geolocator.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:zephyr/core/errors/failures.dart' as _i12;
import 'package:zephyr/core/network/connectivity_service.dart' as _i8;
import 'package:zephyr/core/services/location_service.dart' as _i10;
import 'package:zephyr/data/datasources/local/weather_local_datasource.dart'
    as _i7;
import 'package:zephyr/data/datasources/remote/weather_remote_datasource.dart'
    as _i3;
import 'package:zephyr/data/models/forecast_model.dart' as _i5;
import 'package:zephyr/data/models/search_result_model.dart' as _i6;
import 'package:zephyr/data/models/weather_model.dart' as _i2;
import 'package:zephyr/domain/entities/weather.dart' as _i16;
import 'package:zephyr/domain/usecases/get_current_weather.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherModel_0 extends _i1.SmartFake implements _i2.WeatherModel {
  _FakeWeatherModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i3.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherModel> getCurrentWeather(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [query],
        ),
        returnValue: _i4.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getCurrentWeather,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.WeatherModel>);

  @override
  _i4.Future<List<_i5.ForecastDayModel>> getForecast(
    String? query, {
    int? days = 7,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [query],
          {#days: days},
        ),
        returnValue: _i4.Future<List<_i5.ForecastDayModel>>.value(
            <_i5.ForecastDayModel>[]),
      ) as _i4.Future<List<_i5.ForecastDayModel>>);

  @override
  _i4.Future<List<_i6.SearchResultModel>> searchLocations(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchLocations,
          [query],
        ),
        returnValue: _i4.Future<List<_i6.SearchResultModel>>.value(
            <_i6.SearchResultModel>[]),
      ) as _i4.Future<List<_i6.SearchResultModel>>);
}

/// A class which mocks [WeatherLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDataSource extends _i1.Mock
    implements _i7.WeatherLocalDataSource {
  MockWeatherLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherModel?> getWeather(String? cityKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [cityKey],
        ),
        returnValue: _i4.Future<_i2.WeatherModel?>.value(),
      ) as _i4.Future<_i2.WeatherModel?>);

  @override
  _i4.Future<void> cacheWeather(
    String? cityKey,
    _i2.WeatherModel? weather,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [
            cityKey,
            weather,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>?> getForecast(String? cityKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [cityKey],
        ),
        returnValue: _i4.Future<List<dynamic>?>.value(),
      ) as _i4.Future<List<dynamic>?>);

  @override
  _i4.Future<void> cacheForecast(
    String? cityKey,
    List<dynamic>? forecastJsonList,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            cityKey,
            forecastJsonList,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> toggleFavorite(String? cityName) => (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [cityName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i8.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<_i9.ConnectivityResult> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<_i9.ConnectivityResult>.empty(),
      ) as _i4.Stream<_i9.ConnectivityResult>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i10.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i11.Either<_i12.Failure, _i13.Position>> getCurrentPosition() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i4.Future<_i11.Either<_i12.Failure, _i13.Position>>.value(
            _i14.dummyValue<_i11.Either<_i12.Failure, _i13.Position>>(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i4.Future<_i11.Either<_i12.Failure, _i13.Position>>);
}

/// A class which mocks [GetCurrentWeather].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentWeather extends _i1.Mock implements _i15.GetCurrentWeather {
  MockGetCurrentWeather() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i11.Either<_i12.Failure, _i16.Weather>> execute(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [query],
        ),
        returnValue: _i4.Future<_i11.Either<_i12.Failure, _i16.Weather>>.value(
            _i14.dummyValue<_i11.Either<_i12.Failure, _i16.Weather>>(
          this,
          Invocation.method(
            #execute,
            [query],
          ),
        )),
      ) as _i4.Future<_i11.Either<_i12.Failure, _i16.Weather>>);
}
